### ISSUE TITLE
Visual Studio exception when trying to open Mole 2015 visualizer

### ISSUE THREAD

**Issue by Bokkeman** [Oceanware/Mole2015#1]
VS2015 (with Update 2 installed) throws an Access is denied exception when I'm debugging and try to open the Mole visualizer. All the projects in my solution are configured to compile to .NET 4.6.1 (I changed them to match the SKU in the Mole assembly config file).

PS, and perhaps related: The installation instruction `In Windows Explorer, right-click the downloaded zip file, click the "unblock" check box` does not seem relevant, I do not see and have never seen an Unblock menu item in the context menu for zip files? Was that meant to clear the "insecure origin" windows flag? I have checked the Mole .DLL in my VS2015 Visualizers folder and gave Everyone execute permissions on it.

`Microsoft.VisualStudio.DebuggerVisualizers.DebugViewerShim.RemoteObjectSourceException: Could not load file or assembly 'file:///C:\Users\Bokkeman\Documents\Visual Studio 2015\Visualizers\Mole.Visualizer.VS2015.dll' or one of its dependencies. Access is denied. ---> System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\Bokkeman\Documents\Visual Studio 2015\Visualizers\Mole.Visualizer.VS2015.dll' or one of its dependencies. Access is denied.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
<snip>`

**Comment by kdawg1406** [comment]
Do me a favor and open a new wpf project, add a button, add a click event handler, set a break point in the button click handler, run the app, click the button and open Mole.

Does it open?

BTW:  What is your project type?  What is the type of variable that is in the Data Tip used to open Mole.

Install instructions are to remove the Mark of the Web flag on the file.  I find myself always having to do this.

Karl

**Comment by Bokkeman** [comment]
Mole works fine for the WPF project as requested. Been a while since I've opened a Windows project!
My current project is a web project - ASP.NET MVC4 and I was trying to inspect a collection object. I tried again with a simple string but Mole still won't load.

**Comment by kdawg1406** [comment]
OK, let's see if we can sort this out.  Does the below help?

Are you using IIS?

When using Mole with ASP.NET projects that utilize IIS as the web server, as opposed to the Visual Studio's built in web server, you **MUST give the account that the web site is running under, Read and Read & Execute permissions to the \Visualizers directory.**

If you do not do this, you will get an exception when attempting to load the visualizer in a debugging session. You would get this exception for any visualizer and not just Mole. This is because the ASPNET account has very few permissions on your computer. Adding these permissions prevents this exception.

**Comment by Bokkeman** [comment]
That is exactly what it was - thank you very much. Can I suggest an additional note in the installation instructions to save others from the same fate.
And thank you also for resurrecting the Mole. It saved my bacon in the early years of WPF; it will be interesting to see how useful it is while developing for the web.

**Comment by kdawg1406** [comment]
Great, so glad we sorted this out.

Yes, I'll add this note to the docs.

Best,

Karl
