### ISSUE TITLE
Support DebuggerDisplayAttribute

### ISSUE THREAD

**Issue by Sebazzz** [Oceanware/Mole2015#2]
Mole currently requires overriding ToString, else the data display is useless because you can only see the type names of an object. It would be great if Mole supported the `DebuggerDisplayAttribute`.

**Comment by kdawg1406** [comment]
@Sebazzz I'm going to remove Strings from Moles types to visualize in the next release.  

Thank you for your suggestion and feedback.

**Comment by Sebazzz** [comment]
If I may suggest another alternative, which may be easier to implement for now: Being able to enter a 'property path' for the string representation. For example `inputObject.MyProperty.MyString`.

**Comment by kdawg1406** [comment]
I spent hours trying to upgrade this extension to VS 2019. I've given up. If you want to continue to use this, please make any changes you need to be successful.
